version: "3.10"

services:
  mongo:
    image: mongo:6
    command: [--replSet, my-replica-set, --bind_ip_all, --port, "30001"]
    ports:
      - "30001:30001"
    healthcheck:
      test: test $$(mongosh --port 30001 --quiet --eval "try {rs.initiate({_id:'my-replica-set',members:[{_id:0,host:\"localhost:30001\"}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      start_period: 30s
