//! Hook for observing raw FIX wire bytes in both directions.
//!
//! Implementations receive the unmodified bytes that crossed the session
//! boundary, including session/admin messages (Logon, Heartbeat, Logout,
//! Reject, ResendRequest, SequenceReset, TestRequest) which the
//! [`crate::Application`] trait does not expose.
//!
//! ## Use cases
//!
//! - Lossless capture for replay / post-incident analysis. The bytes
//!   here are exactly what crossed the socket — no Display formatting,
//!   no SOH-to-pipe substitution.
//! - Compliance archives that need every byte the session sent or
//!   received, admin and application alike.
//! - Out-of-band metrics (counts, sizes) where the application-level
//!   `on_inbound_message` hook is too narrow.
//!
//! ## Performance
//!
//! Methods are called from inside the engine's hot path. Implementations
//! must be cheap and non-blocking. If the observer needs to do real I/O,
//! it should write to a channel or a memory buffer here and do the
//! actual I/O on a separate task.
//!
//! Both methods have empty defaults; observers only implement the
//! direction they care about.

use std::sync::Arc;

pub trait WireObserver: Send + Sync {
    /// Called for every inbound FIX message, before parsing. `bytes`
    /// is the raw wire form including SOH delimiters and the trailing
    /// CheckSum field. Includes admin messages (Logon, Heartbeat,
    /// Logout, etc.), which `Application::on_inbound_message` does not.
    fn on_inbound_bytes(&self, _bytes: &[u8]) {}

    /// Called for every outbound FIX message after a successful socket
    /// write. `bytes` is the raw wire form. Includes admin messages
    /// generated by the session layer (Logon, Heartbeat, Logout, etc.)
    /// in addition to messages produced by the application.
    fn on_outbound_bytes(&self, _bytes: &[u8]) {}
}

/// Optional observer carried by the session and writer actors. `None`
/// means no observer; calls become free.
pub type WireObserverHandle = Option<Arc<dyn WireObserver>>;
