name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  code-quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check formatting
        run: cargo fmt --check
      - name: Run clippy
        run: cargo clippy -- -Dclippy::all -D warnings
      - name: Run clippy (all targets and features)
        run: cargo clippy --all-targets --all-features -- -Dclippy::all -D warnings

  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      mongodb: ${{ steps.filter.outputs.mongodb }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Detect path changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            mongodb:
              - 'crates/hotfix-store-mongodb/**'
              - 'crates/hotfix-store/**'

  coverage-core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage (excluding MongoDB)
        run: cargo llvm-cov --all-features --workspace --exclude hotfix-store-mongodb --lcov --output-path lcov.info
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          dry_run: ${{ vars.CODECOV_DRY_RUN == 'true'}}
          flags: core
          files: lcov.info

  coverage-mongodb:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.mongodb == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate MongoDB coverage
        run: cargo llvm-cov --all-features --package hotfix-store-mongodb --lcov --output-path lcov.info
      - name: Upload MongoDB coverage
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          dry_run: ${{ vars.CODECOV_DRY_RUN == 'true'}}
          flags: mongodb
          files: lcov.info
